from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from .db import CatalogItem, Settings


STARTER_CATALOG: list[dict[str, object]] = [
    {
        "code": "GOV-001",
        "title": "Information Security Policy",
        "area": "Governance",
        "description_en": "Core policy that defines the security direction, scope, and commitment.",
        "description_sv": "Grundpolicy som beskriver riktning, omfattning och ansvar for informationssakerhet.",
        "required": True,
        "default_owner_role": "CISO / Security lead",
        "review_frequency_months": 12,
        "tisax_tags": ["policy", "governance"],
    },
    {
        "code": "GOV-002",
        "title": "Scope and Context Register",
        "area": "Governance",
        "description_en": "Defines business scope, assets, locations, and interfaces relevant to the TISAX assessment.",
        "description_sv": "Beskriver verksamhetens scope, tillgangar, platser och granssnitt for TISAX-bedomningen.",
        "required": True,
        "default_owner_role": "Quality manager",
        "review_frequency_months": 12,
        "tisax_tags": ["scope", "register"],
    },
    {
        "code": "GOV-003",
        "title": "Risk Assessment Method",
        "area": "Governance",
        "description_en": "Method and criteria used to identify, evaluate, and treat information security risks.",
        "description_sv": "Metod och kriterier for att identifiera, vardera och behandla informationssakerhetsrisker.",
        "required": True,
        "default_owner_role": "Risk owner",
        "review_frequency_months": 12,
        "tisax_tags": ["risk", "method"],
    },
    {
        "code": "GOV-004",
        "title": "Risk Treatment Plan",
        "area": "Governance",
        "description_en": "Tracked plan for reducing or accepting information security risks.",
        "description_sv": "Plan for att reducera eller acceptera informationssakerhetsrisker.",
        "required": True,
        "default_owner_role": "Risk owner",
        "review_frequency_months": 6,
        "tisax_tags": ["risk", "treatment"],
    },
    {
        "code": "ASM-001",
        "title": "Asset Inventory",
        "area": "Asset Management",
        "description_en": "Inventory of critical information, systems, and devices within scope.",
        "description_sv": "Inventering av kritisk information, system och enheter inom scope.",
        "required": True,
        "default_owner_role": "IT manager",
        "review_frequency_months": 6,
        "tisax_tags": ["assets", "inventory"],
    },
    {
        "code": "ASM-002",
        "title": "Information Classification Guideline",
        "area": "Asset Management",
        "description_en": "Defines classification levels and handling requirements for information.",
        "description_sv": "Definierar klassningsnivaer och hanteringskrav for information.",
        "required": True,
        "default_owner_role": "Information owner",
        "review_frequency_months": 12,
        "tisax_tags": ["classification", "handling"],
    },
    {
        "code": "ACC-001",
        "title": "Access Control Policy",
        "area": "Access Management",
        "description_en": "Rules for provisioning, approval, and periodic review of access rights.",
        "description_sv": "Regler for provisionering, godkannande och periodisk granskning av behorigheter.",
        "required": True,
        "default_owner_role": "IT manager",
        "review_frequency_months": 12,
        "tisax_tags": ["access", "policy"],
    },
    {
        "code": "ACC-002",
        "title": "User Access Review Log",
        "area": "Access Management",
        "description_en": "Evidence of regular access review for systems in scope.",
        "description_sv": "Bevis pa regelbunden genomgang av behorigheter for system inom scope.",
        "required": True,
        "default_owner_role": "System owner",
        "review_frequency_months": 3,
        "tisax_tags": ["access", "review"],
    },
    {
        "code": "ACC-003",
        "title": "Privileged Access Register",
        "area": "Access Management",
        "description_en": "Tracked list of privileged users and the justification for elevated access.",
        "description_sv": "Register over privilegierade anvandare och motiv for forhojd behorighet.",
        "required": True,
        "default_owner_role": "IT manager",
        "review_frequency_months": 3,
        "tisax_tags": ["access", "privileged"],
    },
    {
        "code": "OPS-001",
        "title": "Logging and Monitoring Procedure",
        "area": "Operations",
        "description_en": "Describes what is logged, how alerts are handled, and how evidence is retained.",
        "description_sv": "Beskriver vad som loggas, hur larm hanteras och hur bevis sparas.",
        "required": True,
        "default_owner_role": "Operations lead",
        "review_frequency_months": 12,
        "tisax_tags": ["monitoring", "operations"],
    },
    {
        "code": "OPS-002",
        "title": "Backup and Restore Procedure",
        "area": "Operations",
        "description_en": "Documents backup frequency, retention, protection, and restore testing.",
        "description_sv": "Dokumenterar backupfrekvens, retention, skydd och tester av aterlasning.",
        "required": True,
        "default_owner_role": "IT operations",
        "review_frequency_months": 6,
        "tisax_tags": ["backup", "restore"],
    },
    {
        "code": "OPS-003",
        "title": "Change Management Procedure",
        "area": "Operations",
        "description_en": "Defines how changes are requested, assessed, approved, and documented.",
        "description_sv": "Definierar hur andringar begars, bedoms, godkanns och dokumenteras.",
        "required": True,
        "default_owner_role": "Operations lead",
        "review_frequency_months": 12,
        "tisax_tags": ["change", "operations"],
    },
    {
        "code": "OPS-004",
        "title": "Vulnerability Management Process",
        "area": "Operations",
        "description_en": "Explains patching, vulnerability review, and remediation follow-up.",
        "description_sv": "Forklarar patchning, sarbarhetsgranskning och uppfoljning av atgarder.",
        "required": True,
        "default_owner_role": "Security operations",
        "review_frequency_months": 3,
        "tisax_tags": ["vulnerability", "patching"],
    },
    {
        "code": "INC-001",
        "title": "Incident Response Procedure",
        "area": "Incident Management",
        "description_en": "Defines classification, escalation, communication, and post-incident review.",
        "description_sv": "Definierar klassning, eskalering, kommunikation och efteranalys av incidenter.",
        "required": True,
        "default_owner_role": "Incident manager",
        "review_frequency_months": 12,
        "tisax_tags": ["incident", "response"],
    },
    {
        "code": "INC-002",
        "title": "Incident Log",
        "area": "Incident Management",
        "description_en": "Tracked record of incidents, root causes, actions, and lessons learned.",
        "description_sv": "Journal over incidenter, rotorsaker, atgarder och larande.",
        "required": True,
        "default_owner_role": "Incident manager",
        "review_frequency_months": 1,
        "tisax_tags": ["incident", "evidence"],
    },
    {
        "code": "BCM-001",
        "title": "Business Continuity Plan",
        "area": "Continuity",
        "description_en": "Plan for maintaining critical operations during disruption.",
        "description_sv": "Plan for att uppratthalla kritiska processer vid storningar.",
        "required": True,
        "default_owner_role": "Operations manager",
        "review_frequency_months": 12,
        "tisax_tags": ["continuity", "bcp"],
    },
    {
        "code": "BCM-002",
        "title": "Disaster Recovery Plan",
        "area": "Continuity",
        "description_en": "Restoration plan for systems and services after a major outage.",
        "description_sv": "Aterstallningsplan for system och tjanster efter ett storre avbrott.",
        "required": True,
        "default_owner_role": "IT manager",
        "review_frequency_months": 12,
        "tisax_tags": ["continuity", "drp"],
    },
    {
        "code": "BCM-003",
        "title": "Continuity Test Evidence",
        "area": "Continuity",
        "description_en": "Evidence from continuity or restore exercises and corrective actions.",
        "description_sv": "Bevis fran kontinuitets- eller aterlasningstester samt korrigerande atgarder.",
        "required": True,
        "default_owner_role": "Operations manager",
        "review_frequency_months": 6,
        "tisax_tags": ["continuity", "test"],
    },
    {
        "code": "SUP-001",
        "title": "Supplier Security Assessment",
        "area": "Supplier Management",
        "description_en": "Evaluation of suppliers that access, process, or host scoped information.",
        "description_sv": "Bedomning av leverantorer som far tillgang till, behandlar eller hostar scoped information.",
        "required": True,
        "default_owner_role": "Procurement",
        "review_frequency_months": 12,
        "tisax_tags": ["supplier", "assessment"],
    },
    {
        "code": "SUP-002",
        "title": "Supplier Register",
        "area": "Supplier Management",
        "description_en": "List of relevant suppliers, services, owners, and review status.",
        "description_sv": "Lista over relevanta leverantorer, tjanster, agare och granskningsstatus.",
        "required": True,
        "default_owner_role": "Procurement",
        "review_frequency_months": 6,
        "tisax_tags": ["supplier", "register"],
    },
    {
        "code": "HR-001",
        "title": "Security Awareness Training Record",
        "area": "Human Resources",
        "description_en": "Tracks onboarding and periodic security awareness completion.",
        "description_sv": "Sparar introduktions- och aterkommande sakerhetsutbildning.",
        "required": True,
        "default_owner_role": "HR",
        "review_frequency_months": 12,
        "tisax_tags": ["training", "hr"],
    },
    {
        "code": "HR-002",
        "title": "Joiner Mover Leaver Procedure",
        "area": "Human Resources",
        "description_en": "Procedure for secure onboarding, role changes, and offboarding.",
        "description_sv": "Process for saker introduktion, rollandringar och avslut.",
        "required": True,
        "default_owner_role": "HR",
        "review_frequency_months": 12,
        "tisax_tags": ["hr", "access"],
    },
    {
        "code": "PHY-001",
        "title": "Physical Security Procedure",
        "area": "Physical Security",
        "description_en": "Rules for site access, visitor handling, and restricted areas.",
        "description_sv": "Regler for platsbehorighet, besokshantering och restriktiva omraden.",
        "required": True,
        "default_owner_role": "Facilities",
        "review_frequency_months": 12,
        "tisax_tags": ["physical", "facility"],
    },
    {
        "code": "PHY-002",
        "title": "Visitor Log",
        "area": "Physical Security",
        "description_en": "Evidence that visitors are tracked and handled according to the procedure.",
        "description_sv": "Bevis pa att besokare registreras och hanteras enligt process.",
        "required": False,
        "default_owner_role": "Facilities",
        "review_frequency_months": 1,
        "tisax_tags": ["physical", "visitor"],
    },
    {
        "code": "DAT-001",
        "title": "Data Retention and Disposal Procedure",
        "area": "Data Protection",
        "description_en": "Explains retention periods, secure deletion, and disposal controls.",
        "description_sv": "Forklarar bevarandetider, saker radering och avvecklingskontroller.",
        "required": True,
        "default_owner_role": "Information owner",
        "review_frequency_months": 12,
        "tisax_tags": ["data", "retention"],
    },
    {
        "code": "DAT-002",
        "title": "Encryption Standard",
        "area": "Data Protection",
        "description_en": "Standard for encryption in transit, at rest, and key handling.",
        "description_sv": "Standard for kryptering under overforing, lagring och nyckelhantering.",
        "required": True,
        "default_owner_role": "Security architect",
        "review_frequency_months": 12,
        "tisax_tags": ["encryption", "data"],
    },
]


def seed_initial_data(session: Session) -> None:
    has_catalog = session.scalar(select(CatalogItem.id).limit(1))
    if not has_catalog:
        session.add_all(CatalogItem(**item) for item in STARTER_CATALOG)

    settings = session.get(Settings, 1)
    if settings is None:
        session.add(Settings(id=1, workspace_name="QualityDoc", notification_enabled=False, due_soon_days=30))

    session.commit()
